### PR TITLE
Fix bugs and add looking through current file's directory

### PR DESCRIPTION
**Pull request by didedoshka**
Hi. I have been using your plugin for some time and need it for my work. 

### Things I changed
- fix bug that history appends twice
- fix bug that when there are more than 10 items in history the most recent is deleted, not the least
- add support for workspaces with more than one directory
- create new livegrep.searchCurrent command to search through current file's directory
- fix that with new vsce plugin doesn't build

### CODE REVIEW

**Comment by abayomi185** [comment]
Hi, thanks for the PR! I got your email.
I'll get this checked out and tested in the next few hours.

**Comment by abayomi185** [comment]
Thanks! Will get this deployed

**Comment by abayomi185** [comment]
It's live now

**Comment by didedoshka** [comment]
> It's live now

I believe it doesn't work now as is. Didn't notice since I used my fork, could you check what you additionally changed?

**Comment by abayomi185** [comment]
Ok. Will check

**Comment by abayomi185** [comment]
Strangely, it works fine locally on main

**Comment by didedoshka** [comment]
> Strangely, it works fine locally on main

Try to install from vscode extension store. If it works for you I can provide more bug report

**Comment by didedoshka** [comment]
image
image

And it's like that on both my mac computers. When I install from my fork it works fine

**Comment by abayomi185** [comment]
I can reproduce the error from the version on the store. Investigating it.

**Comment by abayomi185** [comment]
I found the issue and uploaded the patch to the store. The extension should work now

**Comment by abayomi185** [comment]
Thanks!

**Comment by didedoshka** [comment]
> I found the issue and uploaded the patch to the store. The extension should work now

It does, thanks!

**Pull request merged**
